import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { createRailway } from '../../../src/railway';
import { requireTokenFromEnv } from '../../../src/auth';
import type { TokenType } from '../../../src/auth';
import { TEMPLATE_CODE } from './config';

interface TemplateTypeInfo {
  code: string;
  name: string;
  typeName: string;
  config: unknown;
}

interface GenerateOptions {
  templates: string[];
  token: string;
  tokenType?: TokenType;
}

interface GenerateResult {
  types: string;
  templates: TemplateTypeInfo[];
}

const toPascalCase = (str: string): string => {
  return str
    .split(/[-_\s]+/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('');
};

const toConstantCase = (str: string): string => {
  return str.toUpperCase().replace(/-/g, '_');
};

const serializeValue = (value: unknown, indent = 0): string => {
  const spaces = '  '.repeat(indent);

  if (value === null) return 'null';
  if (value === undefined) return 'undefined';

  switch (typeof value) {
    case 'string':
      return JSON.stringify(value);
    case 'number':
    case 'boolean':
      return String(value);
    case 'object': {
      if (Array.isArray(value)) {
        if (value.length === 0) return '[]';
        const items = value.map((v) => serializeValue(v, indent + 1)).join(', ');
        return `[${items}]`;
      }

      const entries = Object.entries(value as Record<string, unknown>);
      if (entries.length === 0) return '{}';

      const props = entries
        .map(([key, val]) => {
          const safeKey = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : `'${key}'`;
          return `${spaces}  ${safeKey}: ${serializeValue(val, indent + 1)},`;
        })
        .join('\n');

      return `{\n${props}\n${spaces}}`;
    }
    default:
      return 'undefined';
  }
};

const generateOutput = (templates: TemplateTypeInfo[]): string => {
  const sections: string[] = [];

  const header = `/**
 * Auto-generated Railway template configuration.
 * https://github.com/crisog/railway-sdk/tree/main/examples/templates-advanced
 *
 * Run: tsx --env-file=.env examples/templates-advanced/typegen.ts
 * Do not edit this file manually.
 */

`;
  sections.push(header);

  for (const info of templates) {
    const constName = `${toConstantCase(info.code)}_DEFAULT_CONFIG`;
    const serialized = serializeValue(info.config);

    sections.push(`export const ${constName} = ${serialized};`);
    sections.push(`export type ${info.typeName}Config = typeof ${constName};`);
    sections.push(
      `export const create${info.typeName}Config = (): ${info.typeName}Config =>\n  JSON.parse(JSON.stringify(${constName}));`,
    );
  }

  const templateMapEntries = templates
    .map((info) => `  '${info.code}': ${info.typeName}Config;`)
    .join('\n');

  sections.push(`export interface TemplateConfigMap {\n${templateMapEntries}\n}`);

  return sections.join('\n\n') + '\n';
};

const generateTemplateTypes = async (options: GenerateOptions): Promise<GenerateResult> => {
  const railway = createRailway({
    token: options.token,
    tokenType: options.tokenType ?? 'account',
  });

  const templateInfos: TemplateTypeInfo[] = [];

  for (const code of options.templates) {
    const result = await railway.templates.get({
      variables: { code },
    });

    if (result.isErr()) {
      throw new Error(`Failed to fetch template "${code}": ${result.error.message}`);
    }

    const { template } = result.value;

    if (!template) {
      throw new Error(`Template "${code}" not found`);
    }

    templateInfos.push({
      code: template.code,
      name: template.name,
      typeName: toPascalCase(template.code),
      config: template.serializedConfig,
    });
  }

  const types = generateOutput(templateInfos);

  return { types, templates: templateInfos };
};

async function main() {
  const { token } = requireTokenFromEnv();

  console.log(`Generating config for: ${TEMPLATE_CODE}\n`);

  const result = await generateTemplateTypes({ templates: [TEMPLATE_CODE], token });

  for (const template of result.templates) {
    console.log(`  ✓ ${template.name} (${template.code})`);
  }

  const outputDir = path.join(import.meta.dirname, 'generated');
  const outputFile = path.join(outputDir, `${TEMPLATE_CODE}.ts`);

  await fs.mkdir(outputDir, { recursive: true });
  await fs.writeFile(outputFile, result.types, 'utf-8');

  console.log(`\nOutput: ${outputFile}`);
}

main().catch((error) => {
  console.error('Error:', error instanceof Error ? error.message : error);
  process.exit(1);
});
